apiVersion: apps/v1
kind: Deployment
metadata:
  name: activity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activity-service
  template:
    metadata:
      labels:
        app: activity-service
    spec:
      containers:
        - name: activity-service
          image: olaniyikolawole744/activity-service:2.0
          ports:
            - containerPort: 8001
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DATABASE_URL
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:29092"
            - name: FRONTEND_ORIGIN
              value: "http://localhost:3000"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: activity-service
spec:
  selector:
    app: activity-service
  ports:
    - port: 8001
      targetPort: 8001
  type: ClusterIP